name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkouting...
      uses: actions/checkout@v1
    - name: Bulding...
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm ci
        npm run ng build --prod --baseHref=/angular-submodule-page-1 --deployUrl=/angular-submodule-page-1/
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: dist/first-app
        keep_history: true
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}        

