name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkouting...
      uses: actions/checkout@v1
    - name: Bulding...
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm ci
        npm run build --prod
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: https://github.com/bullwinkle/bullwinkle.github.io.git
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
