name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkouting...
      uses: actions/checkout@v1
    - name: Bulding...
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm ci
        npm run build --prod
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: bullwinkle/bullwinkle.github.io/pages/first-app
        target_branch: master
        build_dir: dist/first-app
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}        

